### ISSUE TITLE
Panic runtime error

### ISSUE THREAD

**Issue by jalberto** [graillus/gcrgc#12]
If I try to run this commadn in my laptop I get this error:

```
$ gcrgc -registry=gcr.io/foo -untagged-only bar                                                                                                  [3/1142]
Fetching repositories in registry [gcr.io/foo]                                                                                                             
5 repositories found                                                                                                                                                         
panic: runtime error: invalid memory address or nil pointer dereference                                                                                                      
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x6aed8a]

goroutine 1 [running]:
github.com/graillus/gcrgc/pkg/gcrgc.getTaskList(0x7c3240, 0xc00005aea0, 0xc000522180, 0x1, 0x1, 0xc000158090, 0x1)
        /home/runner/work/gcrgc/gcrgc/pkg/gcrgc/gcrgc.go:118 +0x1ea
github.com/graillus/gcrgc/pkg/gcrgc.(*App).Start(0xc000133f70)
        /home/runner/work/gcrgc/gcrgc/pkg/gcrgc/gcrgc.go:51 +0x292
main.main()
        /home/runner/work/gcrgc/gcrgc/cmd/gcrgc/gcrgc.go:127 +0x43
```

**Comment by graillus** [comment]
Hi,

I managed to reproduce the error. Looks like it doesn't like to run without a time retention or date threshold. I'm going to fix that.

Try using either `-date` or `-retention-period` options to avoid the issue.

Thanks for the report !

**Comment by graillus** [comment]
@jalberto You can upgrade to version [v0.3.3](https://github.com/graillus/gcrgc/releases/tag/v0.3.3) which contains the fix.

Thanks again for reporting the bug
